---

- name: "CREATE FORTIMANAGER ADDRESS FOR UNIT TESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE ADDRESS OBJECT - CHANGE"
      fortimgr_address:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        address_name: "route_unittest"
        address_type: "ipmask"
        subnet:
          - "10.2.1.1"
          - "255.255.255.255"
        allow_routing: "enable"

- name: "FORTIMANAGER ROUTE UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE ROUTE LIST NOTATION - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE ROUTE AGAIN LIST NOTATION - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE ROUTE CIDR NOTATION - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination: "10.20.10.0/24"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      register: config_results

    - assert:
        that: "config_results['changed']"

    - name: "CREATE ROUTE CIDR NOTATION AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "10.20.10.0/24"
        gateway: "10.1.1.1"
        intfc: "port1"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "SET PROVIDER - NO CHANGE"
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          fortigate: "lab1"
          destination: "10.20.10.0/24"
          gateway: "10.1.1.1"
          intfc: "port1"
          vdom: "root"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE ROUTE WITH PROVIDER - NO CHANGE"
      fortimgr_route:
        provider: "{{ provider }}"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE ROUTE OVERRIDE PROVIDER - CHANGE"
      fortimgr_route:
        provider: "{{ provider }}"
        fortigate: "lab2"
        destination: "10.20.11.0/24"
        gateway: "10.1.1.2"
        intfc: "port2"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE ROUTE HOST NOTATION - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination: "10.20.16.16"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE ROUTE HOST NOTATION AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "10.20.16.16"
        gateway: "10.1.1.1"
        intfc: "port1"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE ROUTE NET AND MASK NOTATION - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_network: "10.30.10.0"
        destination_netmask: "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE ROUTE NET AND MASK NOTATION AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination_network: "10.30.10.0"
        destination_netmask: "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE ROUTE ADDRESS OBJECT - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
      ignore_errors: true

    - name: "CREATE ROUTE ADDRESS OBJECT AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
      ignore_errors: true

    - name: "DELETE ROUTE ADDRESS OBJECT - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
        state: "absent"
      ignore_errors: true

    - name: "DELETE ROUTE ADDRESS OBJECT AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        destination_object: "route_unittest"
        gateway: "10.1.1.1"
        intfc: "port1"
        vdom: "root"
        state: "absent"
      ignore_errors: true

    - name: "ADD ROUTE TO DIFFERENT GATEWAY - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.2"
        intfc: "port1"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY ROUTE'S INTERFACE USING SEQUENCE NUMBER - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        sequence_number: "{{ config_results.config.params[0].data.get('seq-num') }}"
        intfc: "port2"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "ADD ROUTE THROUGH DIFFERENT INTERFACE - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.2"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE MISSING GATEWAY - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE MISSING DESTINATION - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        gateway: "10.1.1.1"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION ADDRESS AND OBJECT - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        destination_object: "route_unittest"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION ADDRESS AND OBJECT PROVIDER - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        provider:
          destination:
            - "10.10.10.0"
            - "255.255.255.0"
          destination_object: "route_unittest"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION ADDRESS AND DESTINATION_NETMASK - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        destination_netmask: "255.255.255.0"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION ADDRESS AND DESTINATION_NETWORK/DESTINATION_NETMASK PROVIDER - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        provider:
          destination:
            - "10.10.10.0"
            - "255.255.255.0"
          destination_netmask: "255.255.255.0"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION_NETWORK W/O DESTINATION_NETMASK - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination_network: "10.10.10.0"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "ADD ROUTE DESTINATION_NETWORK W/O DESTINATION_NETMASK PROVIDER - FAIL"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        provider:
          destination_network: "10.10.10.0"
        intfc: "port2"
      ignore_errors: True
      register: "fmg_results"

    - assert:
        that: "fmg_results['failed']"

    - name: "DELETE ROUTE - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "{{ item }}"
        intfc: "port1"
        state: "absent"
      loop:
        - "10.1.1.1"
        - "10.1.1.2"
      tags: "cleanup"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE ROUTE AGAIN - NO CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination:
          - "10.10.10.0"
          - "255.255.255.0"
        gateway: "10.1.1.1"
        intfc: "port1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "DELETE ROUTE - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab1"
        vdom: "root"
        destination: "{{ item }}"
        gateway: "10.1.1.1"
        intfc: "port1"
        state: "absent"
      loop:
        - "10.20.10.0/24"
        - "10.30.10.0/24"
        - "10.20.16.16"
      tags: "cleanup"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE ROUTE FROM OVERRIDE PROVIDER - CHANGE"
      fortimgr_route:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        fortigate: "lab2"
        vdom: "root"
        destination: "10.20.11.0/24"
        gateway: "10.1.1.2"
        intfc: "port2"
        state: "absent"
      tags: "cleanup"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"
      register: "fmg_results"


- name: "DELETE FORTIMANAGER ADDRESS FOR UNIT TESTS"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "DELETE ADDRESS OBJECT - CHANGE"
      fortimgr_address:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        address_name: "route_unittest"
        address_type: "ipmask"
        subnet:
          - "10.2.1.1"
          - "255.255.255.255"
        state: "absent"