---
- name: "CREATE FORTIMANAGER SERVICES FOR UNIT TESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE SERVICE - CHANGE"
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "{{ item.name }}"
        protocol: "TCP"
        port_range:
          - "{{ item.port }}"
      loop:
        - name: "svc1"
          port: 1
        - name: "svc2"
          port: 2
        - name: "svc3"
          port: 3
        - name: "svc4"
          port: 4


- name: "FORTIMANAGER SERVICE GROUP UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE SERVICE GROUP - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"
        color: 18
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE SERVICE GROUP AGAIN - NO CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"
        color: "18"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "SET PROVIDER - NO CHANGE"
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          service_group_name: "svcgrp1"
          members: "svc1"
          comment: "service group unit test"
          color: "18"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE SERVICE GROUP WITH PROVIDER - NO CHANGE"
      fortimgr_service_group:
        provider: "{{ provider }}"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE SERVICE GROUP OVERRIDE PROVIDER - CHANGE"
      fortimgr_service_group:
        provider: "{{ provider }}"
        service_group_name: "provider_svcgrp1"
        members:
          - "svc3"
          - "svc4"
        comment: "service group unit test"
        color: 14
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY SERVICE GROUP ADD MEMBER WITH EXISTING MEMBERS - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
          - "svc3"
        comment: "service group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY SERVICE GROUP ADD MEMBER WITHOUT EXISTING MEMBERS - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc4"
        comment: "service group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY SERVICE GROUP REMOVE MEMBER - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        state: "param_absent"
        comment: "service group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY SERVICE GROUP REMOVE MEMBER AGAIN - NO CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc1"
          - "svc2"
        state: "param_absent"
        comment: "service group unit test"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE SERVICE GROUP - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp2"
        members:
          - "svc1"
          - "svc2"
        comment: "service group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE SERVICE GROUP WITH PARAMS - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        members:
          - "svc3"
          - "svc4"
        comment: "service group unit test"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE SERVICE GROUP AGAIN - NO CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "svcgrp1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"


- name: "CLEANUP FORTIMANAGER SERVICES FOR UNIT TESTS"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "CLEANUP SERVICE GROUPS - CHANGE"
      fortimgr_service_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_group_name: "{{ item.name }}"
        state: "absent"
      loop:
        - name: "svcgrp1"
        - name: "svcgrp2"
        - name: "provider_svcgrp1"

    - name: "CLEANUP SERVICES - CHANGE"
      fortimgr_service:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        service_name: "{{ item.name }}"
        state: "absent"
      loop:
        - name: "svc1"
        - name: "svc2"
        - name: "svc3"
        - name: "svc4"
