---
- name: "FORTIMANAGER IP POOL UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE IP POOL OVERLOAD PERMIT ANY - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool1"
        type: "overload"
        permit_any_host: "enable"
        start_ip: "100.10.10.1"
        end_ip: "100.10.10.1"
        comment: "pool unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE IP POOL OVERLOAD AGAIN - NO CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool1"
        type: "overload"
        permit_any_host: "enable"
        start_ip: "100.10.10.1"
        end_ip: "100.10.10.1"
        comment: "pool unit test"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "SET PROVIDER - NO CHANGE"
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          pool_name: "pool1"
          type: "overload"
          permit_any_host: "enable"
          start_ip: "100.10.10.1"
          end_ip: "100.10.10.1"
          comment: "pool unit test"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE IP POOL OVERLOAD PERMIT ANY WITH PROVIDER- NO CHANGE"
      fortimgr_ip_pool:
        provider: "{{ provider }}"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE IP POOL OVERLOAD PERMIT ANY OVERRIDE PROVIDER - CHANGE"
      fortimgr_ip_pool:
        provider: "{{ provider }}"
        pool_name: "provider_pool1"
        type: "overload"
        permit_any_host: "disable"
        start_ip: "100.10.10.2"
        end_ip: "100.10.10.2"
        comment: "provider pool unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE IP POOL OVERLOAD INCREASE POOL RANGE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool1"
        end_ip: "100.10.10.2"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE IP POOL ONE-TO-ONE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool2"
        type: "one-to-one"
        start_ip: "100.10.21.1"
        end_ip: "100.10.21.1"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE IP POOL ONE-TO-ONE AGAIN - NO CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool2"
        type: "one-to-one"
        start_ip: "100.10.21.1"
        end_ip: "100.10.21.1"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE IP POOL FIXED-PORT-RANGE RESTRICT SOURCE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool3"
        type: "fixed-port-range"
        start_ip: "100.10.30.1"
        end_ip: "100.10.30.10"
        permit_any_host: "disable"
        source_start_ip: "10.10.30.1"
        source_end_ip: "10.10.30.10"
        comment: "pool unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE IP POOL FIXED-PORT-RANGE RESTRICT SOURCE AGAIN - NO CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool3"
        type: "fixed-port-range"
        start_ip: "100.10.30.1"
        end_ip: "100.10.30.10"
        permit_any_host: "disable"
        source_start_ip: "10.10.30.1"
        source_end_ip: "10.10.30.10"
        comment: "pool unit test"
      register: "not fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY IP POOL FIXED-PORT-RANGE SOURCE RANGE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool3"
        source_end_ip: "10.10.30.20"
        comment: "pool unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE IP POOL OVERLOAD PERMIT ANY - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool1"
        type: "overload"
        permit_any_host: "enable"
        start_ip: "100.10.10.1"
        end_ip: "100.10.10.1"
        comment: "pool unit test"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE IP POOL OVERLOAD PERMIT ANY AGAIN - NO CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool1"
        type: "overload"
        permit_any_host: "enable"
        start_ip: "100.10.10.1"
        end_ip: "100.10.10.1"
        comment: "pool unit test"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "DELETE IP POOL ONE-TO-ONE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool2"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE IP POOL ONE-TO-ONE - CHANGE"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "pool3"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"


- name: "CLEANUP FORTIMANAGER IP POOLS"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "CLEANUP IP POOL ENTRIES"
      fortimgr_ip_pool:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        pool_name: "{{ item }}"
        state: "absent"
      loop:
        - "pool1"
        - "pool2"
        - "pool3"
        - "provider_pool1"

