---
- name: "FORTIMANAGER ADDRESS UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE REVISION - CHANGE"
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        created_by: "ansible"
        description: "revision unittest 1"
        revision_name: "unittest1"

    - name: "CREATE ANOTHER REVISION WITH PROVIDER - CHANGE"
      fortimgr_revision:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          created_by: "ansible"
          description: "revision unittest 2"
          revision_name: "unittest2"

    - name: "RESTORE REVISION - CHANGE"
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        state: "restore"
        created_by: "ansible"
        description: "restore unittest 1"
        revision_name: "unittest1"
        restore_name: "unittest_restore"

    - name: "DELETE REVISION - CHANGE"
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        created_by: "ansible"
        description: "revision unittest 1"
        revision_name: "unittest1"
      loop:
        - "unittest1"
        - "unittest2"
        - "unittest_restore"
