---
- name: "FORTIMANAGER VIP UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE VIP - CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip1"
        type: "static-nat"
        arp_reply: "enable"
        external_ip:
          - "100.10.10.10"
        mapped_ip: 
          - "10.10.10.10"
        external_intfc: "port1"
        comment: "vip unit test"
        color: 2
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE VIP AGAIN - NO CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip1"
        type: "static-nat"
        arp_reply: "enable"
        external_ip:
          - "100.10.10.10"
        mapped_ip:
          - "10.10.10.10"
        external_intfc: "port1"
        comment: "vip unit test"
        color: 2
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "SET PROVIDER - NO CHANGE"
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          vip_name: "vip1"
          type: "static-nat"
          arp_reply: "enable"
          external_ip: "100.10.10.10"
          mapped_ip: "10.10.10.10"
          external_intfc: "port1"
          comment: "vip unit test"
          color: "2"

    - name: "CREATE VIP WITH PROVIDER - NO CHANGE"
      fortimgr_vip:
        provider: "{{ provider }}"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE VIP OVERRIDE PROVIDER - CHANGE"
      fortimgr_vip:
        provider: "{{ provider }}"
        vip_name: "vip2"
        type: "static-nat"
        arp_reply: "disable"
        external_ip: "100.10.10.11"
        mapped_ip: "10.10.10.11"
        external_intfc: "port2"
        comment: "vip unit test provider"
        color: "5"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY VIP CHANGE EXTERNAL IP - CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip1"
        type: "static-nat"
        arp_reply: "disable"
        external_ip:
          - "100.10.10.11"
        comment: "vip unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE VIP - CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE VIP AGAIN - NO CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "vip1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"


- name: "CLEANUP FORTIMANAGER VIP UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "CLEANUP"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "{{ item }}"
        state: "absent"
      loop:
        - "vip1"
        - "vip2"
