---

- name: "CREATE FORTIMANAGER VIPS FOR UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE VIP - CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "{{ item.name }}"
        type: "static-nat"
        external_ip: 
          - "{{ item.ext }}"
        mapped_ip:
          - "{{ item.map }}"
      loop:
        - name: "vip1"
          ext: "100.10.10.10"
          map: "10.10.10.10"
        - name: "vip2"
          ext: "100.10.10.11"
          map: "10.10.10.11"
        - name: "vip3"
          ext: "100.10.10.12"
          map: "10.10.10.12"
        - name: "vip4"
          ext: "100.10.10.13"
          map: "10.10.10.13"

- name: "FORTIMANAGER VIP GROUP UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE VIP GROUP - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        interface:
          - "port1"
        members:
          - "vip1"
          - "vip2"
        comment: "vip group unit test"
        color: 10
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "CREATE VIP GROUP AGAIN - NO CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        interface:
          - "port1"
        members:
          - "vip1"
          - "vip2"
        comment: "vip group unit test"
        color: 10
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "SET PROVIDER - NO CHANGE"
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          adom: "lab"
          vip_group_name: "vipgrp1"
          interface: "port1"
          members:
            - "vip1"
            - "vip2"
          comment: "vip group unit test"
          color: 10
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE VIP GROUP WITH PROVIDER - NO CHANGE"
      fortimgr_vip_group:
        provider: "{{ provider }}"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "CREATE VIP GROUP OVERRIDE PROVIDER - CHANGE"
      fortimgr_vip_group:
        provider: "{{ provider }}"
        vip_group_name: "provider_vipgrp1"
        interface: "port2"
        members: "vip3"
        comment: "provider vip group unit test"
        color: 15
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY VIP GROUP CHANGE INTERFACE - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        interface:
          - "port2"
        comment: "vip group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY VIP GROUP ADD MEMBER - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        members:
          - "vip3"
        comment: "vip group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY VIP GROUP DELETE MEMBER - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        members:
          - "vip1"
          - "vip2"
        state: "param_absent"
        comment: "vip group unit test"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "MODIFY VIP GROUP DELETE MEMBER AGAIN - NO CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        members:
          - "vip1"
          - "vip2"
        state: "param_absent"
        comment: "vip group unit test"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"

    - name: "DELETE VIP GROUP - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "fmg_results['changed']"

    - name: "DELETE VIP GROUP AGAIN - NO CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "vipgrp1"
        state: "absent"
      register: "fmg_results"

    - assert:
        that: "not fmg_results['changed']"


- name: "CLEANUP FORTIMANAGER VIPs"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "CLEANUP VIP GROUPS - CHANGE"
      fortimgr_vip_group:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_group_name: "{{ item }}"
        state: "absent"
      loop:
        - "vipgrp1"
        - "provider_vipgrp1"

    - name: "CLEANUP VIPS - CHANGE"
      fortimgr_vip:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        vip_name: "{{ item }}"
        state: "absent"
      loop:
        - "vip1"
        - "vip2"
        - "vip3"
        - "vip4"
