---
- name: "FORTIMANAGER GENERATE INSTALL DATA"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "CREATE ADDRESS IPMASK - CHANGE"
      fortimgr_address:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        address_name: "addr1"
        address_type: "ipmask"
        subnet:
          - "10.1.1.1"
          - "255.255.255.255"
        comment: "ipmask unit test"

    - name: "CREATE POLICY THAT USES ADDRESS - CHANGE"
      fortimgr_policy:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        package: "lab"
        action: "accept"
        destination_address:
          - "addr1"
        destination_intfc:
          - "any"
        policy_name: "InstallTest"
        schedule:
          - "always"
        service:
          - "ALL"
        source_address:
          - "all"
        source_intfc:
          - "any"

- name: "FORTIMANAGER POLICY INSTALL UNITTESTS"
  hosts: "fortimanager"
  gather_facts: false
  tasks:
    - name: "PREVIEW POLICY PACKAGE - CHANGE"
      fortimgr_install:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        state: "preview"
        dst_file:
        fortigate_name: "FortiGate-VM64-KVM"
        package: "lab"
        vdom: "root"
      ignore_errors: true

    - name: "INSTAL POLICY PACKAGE - CHANGE"
      fortimgr_install:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        state: "preview"
        adom_revision_comments: "Install Unit Test"
        adom_revision_name: "InstallTest"
        check_install: false
        dst_file: "./preview.txt"
        fortigate_name: "FortiGate-VM64-KVM"
        fortigate_revision_comments: "Install Unit Test"
        install_flags:
          - "generate_rev"
        package: "lab"
        vdom: "root"
      ignore_errors: true

    - name: "INSTAL POLICY PACKAGE - NO CHANGE"
      fortimgr_install:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        state: "preview"
        adom_revision_comments: "Install Unit Test"
        adom_revision_name: "InstallTest"
        check_install: false
        dst_file: "./preview.txt"
        fortigate_name: "FortiGate-VM64-KVM"
        fortigate_revision_comments: "Install Unit Test"
        install_flags:
          - "generate_rev"
        package: "lab"
        vdom: "root"
      ignore_errors: true

- name: "FORTIMANAGER CLEANUP INSTALL DATA"
  hosts: "fortimanager"
  gather_facts: false
  tags: "cleanup"
  tasks:
    - name: "CLEANUP POLICY THAT USES ADDRESS - CHANGE"
      fortimgr_policy:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        package: "lab"
        policy_name: "InstallTest"
        state: "absent"

    - name: "CLEANUP ADDRESS IPMASK - CHANGE"
      fortimgr_address:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "lab"
        address_name: "addr1"
        state: "absent"

