---

- name: FORTIMANAGER FACTS UNITTESTS
  hosts: fortimanager
  connection: local
  gather_facts: false
  
  tasks:
    - name: GET BASIC FACTS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: GET FORTIGATE FACTS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates:
          - "lab1"

    - name: GET ALL FORTIGATE FACTS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates: "all"

    - name: GET FORTIGATE FACTS and SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates:
          - name: "lab1"
            vdom: "root"
        fortigate_name: "hostname"
        config_filter:
          - "policy"
          - "route"

    - name: GET ALL FORTIGATE FACTS AND SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates: "all"
        config_filter:
          - "address"
          - "service"

    - name: GET ALL FORTIGATE FACTS AND ALL CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates: "all"
        config_filter: "all"

    - name: GET ALL FORTIMANAGER FACTS AND ALL CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adoms: "all"
        config_filter: "all"

    - name: GET ALL FORTIMANAGER FACTS AND SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adoms: "all"
        config_filter:
          - "address"
          - "policy"

    - name: GET SOME FORTIMANAGER FACTS (LIST) AND SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adoms: "lab"
        config_filter:
          - "vip"
          - "policy"

    - name: GET SOME FORTIMANAGER FACTS (DICT) AND SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        adoms:
          - name: "lab"
            package: "lab"
        config_filter:
          - "ip_pool"
          - "policy"

    - name: GET SOME FORTIGATE FACTS, SOME FORTIMANAGER FACTS, AND SOME CONFIGS
      fortimgr_facts:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        fortigates:
          - name: "lab1"
            vdom: "root"
        adoms: 
          - name: "lab"
            package: "lab"
        config_filter:
          - "address_group"
          - "policy"
